### ISSUE TITLE
Pinned nixpkgs hash mismatch on Nix 2.0?

### ISSUE THREAD

**Issue by pbogdan** [awakesecurity/hocker#38]
When trying to build from the checkout of this repo I receive the following error:

```
error: while evaluating the file '/shared/Code/hocker/nix/17_09.nix':
while evaluating anonymous function at /shared/Code/hocker/nix/fetchNixpkgs.nix:1:1, called from /shared/Code/hocker/nix/17_09.nix:5:3:
while evaluating 'ifThenElse' at /shared/Code/hocker/nix/fetchNixpkgs.nix:8:16, called from /shared/Code/hocker/nix/fetchNixpkgs.nix:12:1:
hash mismatch in file downloaded from 'https://github.com/NixOS/nixpkgs/archive/3389f23412877913b9d22a58dfb241684653d7e9.tar.gz': expected hash 'sha256:1zf05a90d29bpl7j56y20r3kmrl4xkvg7gsfi55n6bb2r0xp2ma5', got 'sha256:0wgm7sk9fca38a50hrsqwz6q79z35gqgb9nw80xz7pfdr4jy9pf8
```

It seems the hash specified is of the tarball itself rather than the unpacked contents (AFAIK `fetchTarball` expects the latter).

**Comment by ixmatus** [comment]
Yes I recognize this issue, thank you for reporting this, we have this fixed elsewhere but I haven't fixed it in this repository.

**Comment by ixmatus** [comment]
Actually, I take that back, we do use the fixed-output `fetchNixpkgs.nix`. I think this might be specific to Nix 2.0 then...

**Comment by ixmatus** [comment]
Oops, wait, I take that back again. This issue is not fixed in our `fetchNixpkgs.nix` but I had fixed it in another repository. I'm pushing a PR now.
