### ISSUE TITLE
Advice on hnix dependency

### ISSUE THREAD

**Issue by paulyoung** [awakesecurity/hocker#47]
I'm trying to use hocker via Nix's `fetchFromGitHub` and `cabal2Nix` but seeing `error: Package 'hnix-0.5.2' in /nix/store/<hash>-source/pkgs/development/haskell-modules/hackage-packages.nix:<line> is marked as broken, refusing to evaluate.`

If I mark it as unbroken, I run into:

```
[12 of 35] Compiling Nix.Expr.Types.Annotated ( src/Nix/Expr/Types/Annotated.hs, dist/build/Nix/Expr/Types/Annotated.o )
```

```
src/Nix/Render.hs:26:17: error:
    • Couldn't match expected type ‘Int’
                  with actual type ‘NonEmpty SourcePos’
    • In the first argument of ‘FancyError’, namely ‘(beg :| [])’
      In the expression:
        FancyError
          (beg :| [])
          (Set.fromList [ErrorFail (show msg) :: ErrorFancy Void])
      In an equation for ‘posAndMsg’:
          posAndMsg beg msg
            = FancyError
                (beg :| [])
                (Set.fromList [ErrorFail (show msg) :: ErrorFancy Void])
   |
26 |     FancyError (beg :| [])
   |                 ^^^^^^^^^

src/Nix/Render.hs:35:28: error:
    • Variable not in scope:
        parseErrorPretty' :: ByteString -> ParseError t0 Void -> [Char]
    • Perhaps you meant ‘parseErrorPretty’ (imported from Text.Megaparsec.Error)
   |
35 |     return $ text $ init $ parseErrorPretty' contents (posAndMsg beg msg)
   |                            ^^^^^^^^^^^^^^^^^
builder for '/nix/store/4si6chlwafprv3fb70pb6sz9f8rk70m3-hnix-0.5.2.drv' failed with exit code 1
cannot build derivation '/nix/store/xvk74c2xb7xrbq8mckcyjsv3qc5j7nvc-hocker-1.0.5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/xvk74c2xb7xrbq8mckcyjsv3qc5j7nvc-hocker-1.0.5.drv' failed
```

Any suggestions?

**Comment by ixmatus** [comment]
@paulyoung I suggest overriding `hnix` with a newer version (0.6.0 might work better for you).

i.e. `cabal2nix hackage://hnix-0.6.0 > hnix.nix` then `hnix = haskellPackages.callPackage ./hnix.nix { };` wherever you have your haskell overides.

**Comment by paulyoung** [comment]
Thanks, that's essentially what I ended up doing. It also involved providing `hnix-store-core`.

I guess I'm wondering why the constraint isn't `>= 0.6.0`.

**Comment by paulyoung** [comment]
In any case, feel free to close this unless you feel there's anything actionable left to do here.

Thanks again!

**Comment by ixmatus** [comment]
@paulyoung I don't know why it was 0.5.2 instead of 0.6.0 tbh. But I'll leave this open so that we can address it in the cabal file.

**Comment by j6carey** [comment]
@ixmatus , I would have to do a deep dive into history to be sure, but probably there was a time when we had to use a post-0.5.2 unreleased version that still had the 0.5.2 version label, at a time before we could use 0.6.0.

**Comment by ixmatus** [comment]
@j6carey that makes sense.
