### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by zaninime** [awakesecurity/hocker#49]
Hi, I pulled this project and tried building `hocker` from the `release.nix` but it fails. It looks like the whole project still relies on 18.09 for packages, too.

Is this project being maintained any longer?

Thanks!

**Comment by ixmatus** [comment]
It is maintained (but probably needs some love) and we actively use it at Awake Security. I'll see about taking some time soon to cleanup build failures, thanks for opening a ticket :)

**Comment by zaninime** [comment]
Awesome! Happy to hear this ;)

**Comment by bhougland18** [comment]
Yes, this is good to hear.  I just ran across this project and I am a newish Nixos user.

**Comment by ixmatus** [comment]
I believe the build failure noted in this issue was fixed by #50. I've also verified that I can nix-build the `hocker` attribute from the `release.nix`.

I'm closing this issue.
