### ISSUE TITLE
Release 1.0.6 to hackage

### ISSUE THREAD

**Issue by maralorn** [awakesecurity/hocker#52]
Hey there!

Apparently [hocker is required in some tests required to go through before we can release nixos 20.09](https://github.com/NixOS/nixpkgs/issues/95517). But it's broken there because version 1.0.5 is to old for our build plan. I tested 1.0.6 though and that seems to work just fine.
We generally avoid source overrides of hackage packages in nixpkgs, so the best and easiest solution would be if you could release 1.0.6 to hackage.

That would help us a lot. Thanks!

**Comment by ixmatus** [comment]
I just uploaded `hocker` to hackage. Thanks for the ticket!
